server:
  port: ${SPRING_PORT:8080}

spring:
  application:
    name: ${SPRING_APP_NAME:spring-security-course}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:root}
      password: ${SPRING_SECURITY_USER_PASSWORD:root}

  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}