server:
  port: ${SPRING_PORT:8080}

spring:
  application:
    name: ${SPRING_APP_NAME:spring-security-course}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:root}
      password: ${SPRING_SECURITY_USER_PASSWORD:root}
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
